version: "3.8"

volumes:
  postdb:
  nextcloud:

networks:
  nextnet:

services:
  db:
    image: postgres
    networks:
      - nextnet
    restart: always
    volumes:
      - postdb:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: nextdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: Galaxy@s2

  app:
    image: nextcloud
    ports:
      - 8080:80
    networks:
      - nextnet
    volumes:
      - nextcloud:/var/www/html
    restart: always
    depends_on:
      - db
    environment:
      NEXTCLOUD_ADMIN_USER: admin
      NEXTCLOUD_ADMIN_PASSWORD: admin
        


