version: "3.8"
  
networks:
  dup_net:
  per_net:
  nex_net:
  syn_net:
  jel_net:

volumes:
  duplicati-data:

services:
  reverse_proxy:
    image: jwilder/nginx-proxy
    container_name: reverse_proxy
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - dup_net
      - syn_net
      - nex_net
      - jel_net
      - per_net

  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
      #    network_mode: host
    expose:
      - "8096"
    ports:
      - "8920:8920"
      - "1900:1900"
      - "7359:7359"
    user: 1001:1001
    volumes:
      - /jellyfin/config:/config
      - /jellyfin/cache:/cache
      - /jellyfin/media:/media
      - /jellyfin/media2:/media2:ro
    environment:
      - VIRTUAL_HOST=jel.dom.net
      - VIRTUAL_PORT=8096
    restart: "unless-stopped"


  duplicati:
    image: duplicati/duplicati
    container_name: duplicati
    expose:
      - "8200"
    networks:
      - dup_net
    volumes:
      - duplicati-data:/data
    environment:
      - VIRTUAL_HOST=dup.dom.net

  syncthing:
    image: syncthing/syncthing
    container_name: syncthing
    expose:
      - "8384"
      - "22000"
        #    ports:
        #      - 8384:8384
        #      - 22000:22000
    networks:
      - dup_net
    volumes:
      - /wherever/sy-sync:/var/syncthing
    environment:
      - STGUIADDRESS=0.0.0.0:8384
      - VIRTUAL_HOST=syn.dom.net
      - VIRTUAL_PORT=8384
