version: "3.8"
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    network_mode: host
      #    ports:
      #- "8096:8096"
      #- "8920:8920"
      #- "1900:1900"
      #- "7359:7359"
    user: 1001:1001
    volumes:
      - /jellyfin/config:/config
      - /jellyfin/cache:/cache
      - /jellyfin/media:/media
      - /jellyfin/media2:/media2:ro
    restart: "unless-stopped"
